# This is a basic workflow to help you get started with Actions
on: [push]
name: build
jobs:
  build:
    name: "build on MacOS"
    runs-on: macOS-latest #, or windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10' # Resolves to the latest point release of GHC 8.8
          cabal-version: '3.6.2.0' # Exact version of Cabal
      - run: cabal build
